# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import postservice_pb2 as postservice__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in postservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PostServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/postservice.PostService/CreatePost',
                request_serializer=postservice__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=postservice__pb2.CreatePostResponse.FromString,
                _registered_method=True)
        self.GetPost = channel.unary_unary(
                '/postservice.PostService/GetPost',
                request_serializer=postservice__pb2.GetPostRequest.SerializeToString,
                response_deserializer=postservice__pb2.GetPostResponse.FromString,
                _registered_method=True)
        self.UpdatePost = channel.unary_unary(
                '/postservice.PostService/UpdatePost',
                request_serializer=postservice__pb2.UpdatePostRequest.SerializeToString,
                response_deserializer=postservice__pb2.UpdatePostResponse.FromString,
                _registered_method=True)
        self.DeletePost = channel.unary_unary(
                '/postservice.PostService/DeletePost',
                request_serializer=postservice__pb2.DeletePostRequest.SerializeToString,
                response_deserializer=postservice__pb2.DeletePostResponse.FromString,
                _registered_method=True)
        self.ListPosts = channel.unary_unary(
                '/postservice.PostService/ListPosts',
                request_serializer=postservice__pb2.ListPostsRequest.SerializeToString,
                response_deserializer=postservice__pb2.ListPostsResponse.FromString,
                _registered_method=True)
        self.ViewPost = channel.unary_unary(
                '/postservice.PostService/ViewPost',
                request_serializer=postservice__pb2.ViewPostRequest.SerializeToString,
                response_deserializer=postservice__pb2.ViewPostResponse.FromString,
                _registered_method=True)
        self.LikePost = channel.unary_unary(
                '/postservice.PostService/LikePost',
                request_serializer=postservice__pb2.LikePostRequest.SerializeToString,
                response_deserializer=postservice__pb2.LikePostResponse.FromString,
                _registered_method=True)
        self.AddComment = channel.unary_unary(
                '/postservice.PostService/AddComment',
                request_serializer=postservice__pb2.AddCommentRequest.SerializeToString,
                response_deserializer=postservice__pb2.AddCommentResponse.FromString,
                _registered_method=True)
        self.GetComments = channel.unary_unary(
                '/postservice.PostService/GetComments',
                request_serializer=postservice__pb2.GetCommentsRequest.SerializeToString,
                response_deserializer=postservice__pb2.GetCommentsResponse.FromString,
                _registered_method=True)


class PostServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LikePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=postservice__pb2.CreatePostRequest.FromString,
                    response_serializer=postservice__pb2.CreatePostResponse.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=postservice__pb2.GetPostRequest.FromString,
                    response_serializer=postservice__pb2.GetPostResponse.SerializeToString,
            ),
            'UpdatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePost,
                    request_deserializer=postservice__pb2.UpdatePostRequest.FromString,
                    response_serializer=postservice__pb2.UpdatePostResponse.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=postservice__pb2.DeletePostRequest.FromString,
                    response_serializer=postservice__pb2.DeletePostResponse.SerializeToString,
            ),
            'ListPosts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPosts,
                    request_deserializer=postservice__pb2.ListPostsRequest.FromString,
                    response_serializer=postservice__pb2.ListPostsResponse.SerializeToString,
            ),
            'ViewPost': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewPost,
                    request_deserializer=postservice__pb2.ViewPostRequest.FromString,
                    response_serializer=postservice__pb2.ViewPostResponse.SerializeToString,
            ),
            'LikePost': grpc.unary_unary_rpc_method_handler(
                    servicer.LikePost,
                    request_deserializer=postservice__pb2.LikePostRequest.FromString,
                    response_serializer=postservice__pb2.LikePostResponse.SerializeToString,
            ),
            'AddComment': grpc.unary_unary_rpc_method_handler(
                    servicer.AddComment,
                    request_deserializer=postservice__pb2.AddCommentRequest.FromString,
                    response_serializer=postservice__pb2.AddCommentResponse.SerializeToString,
            ),
            'GetComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComments,
                    request_deserializer=postservice__pb2.GetCommentsRequest.FromString,
                    response_serializer=postservice__pb2.GetCommentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'postservice.PostService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('postservice.PostService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PostService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/postservice.PostService/CreatePost',
            postservice__pb2.CreatePostRequest.SerializeToString,
            postservice__pb2.CreatePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/postservice.PostService/GetPost',
            postservice__pb2.GetPostRequest.SerializeToString,
            postservice__pb2.GetPostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/postservice.PostService/UpdatePost',
            postservice__pb2.UpdatePostRequest.SerializeToString,
            postservice__pb2.UpdatePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/postservice.PostService/DeletePost',
            postservice__pb2.DeletePostRequest.SerializeToString,
            postservice__pb2.DeletePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/postservice.PostService/ListPosts',
            postservice__pb2.ListPostsRequest.SerializeToString,
            postservice__pb2.ListPostsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/postservice.PostService/ViewPost',
            postservice__pb2.ViewPostRequest.SerializeToString,
            postservice__pb2.ViewPostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LikePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/postservice.PostService/LikePost',
            postservice__pb2.LikePostRequest.SerializeToString,
            postservice__pb2.LikePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/postservice.PostService/AddComment',
            postservice__pb2.AddCommentRequest.SerializeToString,
            postservice__pb2.AddCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/postservice.PostService/GetComments',
            postservice__pb2.GetCommentsRequest.SerializeToString,
            postservice__pb2.GetCommentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
