services:
  api_service:
    build: ./api-gateway
    environment:
      USER_SERVICE_ADDR: user_service:8080
      POST_COMMENT_ADDR: post_comment_service:50051
    ports:
      - "8081:8080"
    depends_on:
      - user_service
      - post_comment_service

  user_service:
    build: ./user-service
    env_file: .env
    environment:
      DB_DNS: postgresql+asyncpg://postgres:postgres@user_service_db:5432/postgres
    ports:
      - "8082:8080"
    depends_on:
      - users_db

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8083:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    depends_on:
      kafka:
        condition: service_healthy

  post_comment_service:
    build: ./post-comment-service
    environment:
      DB_DNS: postgresql+asyncpg://postgres:postgres@post_comment_service_db:5432/postgres
    ports:
      - "50051:50051"
    depends_on:
      kafka:
        condition: service_healthy

  stats_service:
    build: ./stats-service
    environment:
      KAFKA_BOOTSTRAP: kafka:9092
      CH_HOST: clickhouse
      CH_PORT: 9000
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "50052:50051"

  users_db:
    image: postgres:16
    hostname: user_service_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - user_pg_data:/var/lib/postgresql/data

  posts_db:
    image: postgres:16
    hostname: post_comment_service_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - post_pg_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: eLt7zL8OSw2ZJYlMBxlW2A
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 20

  clickhouse:
    image: clickhouse/clickhouse-server:23.10
    hostname: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_PASSWORD: ""

volumes:
  user_pg_data:
    driver: local
  post_pg_data:
    driver: local
  clickhouse_data:
    driver: local