services:
  api_service:
    build: ./api-gateway
    environment:
      USER_SERVICE_ADDR: user_service:8000
    ports:
      - "8000:8000"
    depends_on:
      - user_service

  user_service:
    build: ./user-service
    environment:
      DB_DNS: postgresql+asyncpg://postgres:postgres@user_service_db:5432/postgres
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    hostname: user_service_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local