# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: stats.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x05stats\" \n\rPostIdRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\"F\n\x14PostCountersResponse\x12\r\n\x05views\x18\x01 \x01(\x03\x12\r\n\x05likes\x18\x02 \x01(\x03\x12\x10\n\x08\x63omments\x18\x03 \x01(\x03\",\n\rTimelinePoint\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\"E\n\x0fTimelineRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12!\n\x06metric\x18\x02 \x01(\x0e\x32\x11.stats.MetricKind\"8\n\x10TimelineResponse\x12$\n\x06points\x18\x01 \x03(\x0b\x32\x14.stats.TimelinePoint\"4\n\x0fTopPostsRequest\x12!\n\x06metric\x18\x01 \x01(\x0e\x32\x11.stats.MetricKind\")\n\x07TopPost\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\"1\n\x10TopPostsResponse\x12\x1d\n\x05posts\x18\x01 \x03(\x0b\x32\x0e.stats.TopPost\"4\n\x0fTopUsersRequest\x12!\n\x06metric\x18\x01 \x01(\x0e\x32\x11.stats.MetricKind\")\n\x07TopUser\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03\"1\n\x10TopUsersResponse\x12\x1d\n\x05users\x18\x01 \x03(\x0b\x32\x0e.stats.TopUser*0\n\nMetricKind\x12\t\n\x05VIEWS\x10\x00\x12\t\n\x05LIKES\x10\x01\x12\x0c\n\x08\x43OMMENTS\x10\x02\x32\x98\x02\n\x0cStatsService\x12\x44\n\x0fGetPostCounters\x12\x14.stats.PostIdRequest\x1a\x1b.stats.PostCountersResponse\x12\x42\n\x0fGetPostTimeline\x12\x16.stats.TimelineRequest\x1a\x17.stats.TimelineResponse\x12>\n\x0bGetTopPosts\x12\x16.stats.TopPostsRequest\x1a\x17.stats.TopPostsResponse\x12>\n\x0bGetTopUsers\x12\x16.stats.TopUsersRequest\x1a\x17.stats.TopUsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICKIND']._serialized_start=599
  _globals['_METRICKIND']._serialized_end=647
  _globals['_POSTIDREQUEST']._serialized_start=22
  _globals['_POSTIDREQUEST']._serialized_end=54
  _globals['_POSTCOUNTERSRESPONSE']._serialized_start=56
  _globals['_POSTCOUNTERSRESPONSE']._serialized_end=126
  _globals['_TIMELINEPOINT']._serialized_start=128
  _globals['_TIMELINEPOINT']._serialized_end=172
  _globals['_TIMELINEREQUEST']._serialized_start=174
  _globals['_TIMELINEREQUEST']._serialized_end=243
  _globals['_TIMELINERESPONSE']._serialized_start=245
  _globals['_TIMELINERESPONSE']._serialized_end=301
  _globals['_TOPPOSTSREQUEST']._serialized_start=303
  _globals['_TOPPOSTSREQUEST']._serialized_end=355
  _globals['_TOPPOST']._serialized_start=357
  _globals['_TOPPOST']._serialized_end=398
  _globals['_TOPPOSTSRESPONSE']._serialized_start=400
  _globals['_TOPPOSTSRESPONSE']._serialized_end=449
  _globals['_TOPUSERSREQUEST']._serialized_start=451
  _globals['_TOPUSERSREQUEST']._serialized_end=503
  _globals['_TOPUSER']._serialized_start=505
  _globals['_TOPUSER']._serialized_end=546
  _globals['_TOPUSERSRESPONSE']._serialized_start=548
  _globals['_TOPUSERSRESPONSE']._serialized_end=597
  _globals['_STATSSERVICE']._serialized_start=650
  _globals['_STATSSERVICE']._serialized_end=930
# @@protoc_insertion_point(module_scope)
